version: '3'
services:
  app:
    build: .
    container_name: parking-app
    ports: 
      - '8880:8880'
    restart: on-failure
    depends_on:
      - database
    environment:
      - APP_QIWIKEY=
      - APP_DATABASE_HOST=database
      - APP_DATABASE_PORT=5432
      - APP_DATABASE_USER=postgres
      - APP_DATABASE_PASSWORD=password
      - APP_DATABASE_NAME=parkings

  database:
    image: postgres:latest
    container_name: database
    environment:
      - POSTGRES_USER="postgres"
      - POSTGRES_PASSWORD="password"
      - POSTGRES_DB="parkings"
      - DATABASE_HOST="database"